require("tim.plugins-setup")
require("tim.core.options")
require("tim.core.keymaps")
require("tim.core.colorscheme")
require("tim.plugins.nvim-tree")
require("tim.plugins.lualine")
require("tim.plugins.nvim-cmp")
